import { PracticeSession } from '../../core/types/SessionTypes';

export const STARTER_SESSIONS: PracticeSession[] = [
  {
    id: 'starter-rudiment-builder',
    name: 'Rudiment Builder',
    isStarter: true,
    createdAt: '',
    updatedAt: '',
    blocks: [
      {
        id: 's1b1',
        label: 'Slow warmup',
        tempo: 60,
        timeSignature: { beats: 4, noteValue: 4 },
        subdivision: 'quarter',
        durationMinutes: 4,
      },
      {
        id: 's1b2',
        label: 'Building',
        tempo: 80,
        timeSignature: { beats: 4, noteValue: 4 },
        subdivision: 'eighth',
        durationMinutes: 4,
      },
      {
        id: 's1b3',
        label: 'Push',
        tempo: 100,
        timeSignature: { beats: 4, noteValue: 4 },
        subdivision: 'sixteenth',
        durationMinutes: 4,
      },
      {
        id: 's1b4',
        label: 'Max tempo',
        tempo: 120,
        timeSignature: { beats: 4, noteValue: 4 },
        subdivision: 'sixteenth',
        durationMinutes: 4,
      },
    ],
  },
  {
    id: 'starter-independence',
    name: 'Independence Workout',
    isStarter: true,
    createdAt: '',
    updatedAt: '',
    blocks: [
      {
        id: 's2b1',
        label: '4/4 groove',
        tempo: 90,
        timeSignature: { beats: 4, noteValue: 4 },
        subdivision: 'eighth',
        durationMinutes: 3,
      },
      {
        id: 's2b2',
        label: '3/4 waltz',
        tempo: 90,
        timeSignature: { beats: 3, noteValue: 4 },
        subdivision: 'eighth',
        durationMinutes: 3,
      },
      {
        id: 's2b3',
        label: '5/4 challenge',
        tempo: 80,
        timeSignature: { beats: 5, noteValue: 4 },
        subdivision: 'eighth',
        durationMinutes: 3,
      },
      {
        id: 's2b4',
        label: '7/8 odd meter',
        tempo: 70,
        timeSignature: { beats: 7, noteValue: 8 },
        subdivision: 'eighth',
        durationMinutes: 3,
      },
    ],
  },
  {
    id: 'starter-groove-warmup',
    name: 'Groove Warmup',
    isStarter: true,
    createdAt: '',
    updatedAt: '',
    blocks: [
      {
        id: 's3b1',
        label: 'Easy feel',
        tempo: 70,
        timeSignature: { beats: 4, noteValue: 4 },
        subdivision: 'eighth',
        durationMinutes: 3,
      },
      {
        id: 's3b2',
        label: 'Building',
        tempo: 85,
        timeSignature: { beats: 4, noteValue: 4 },
        subdivision: 'eighth',
        durationMinutes: 2,
      },
      {
        id: 's3b3',
        label: '16th feel',
        tempo: 85,
        timeSignature: { beats: 4, noteValue: 4 },
        subdivision: 'sixteenth',
        durationMinutes: 3,
      },
      {
        id: 's3b4',
        label: 'Locked in',
        tempo: 100,
        timeSignature: { beats: 4, noteValue: 4 },
        subdivision: 'sixteenth',
        durationMinutes: 2,
      },
    ],
  },
  {
    id: 'starter-blast-beat',
    name: 'Blast Beat Builder',
    isStarter: true,
    createdAt: '',
    updatedAt: '',
    blocks: [
      {
        id: 's4b1',
        label: 'Foundation',
        tempo: 140,
        timeSignature: { beats: 4, noteValue: 4 },
        subdivision: 'sixteenth',
        durationMinutes: 2,
      },
      {
        id: 's4b2',
        label: 'Pushing',
        tempo: 160,
        timeSignature: { beats: 4, noteValue: 4 },
        subdivision: 'sixteenth',
        durationMinutes: 2,
      },
      {
        id: 's4b3',
        label: 'Fast',
        tempo: 180,
        timeSignature: { beats: 4, noteValue: 4 },
        subdivision: 'sixteenth',
        durationMinutes: 2,
      },
      {
        id: 's4b4',
        label: 'Max speed',
        tempo: 200,
        timeSignature: { beats: 4, noteValue: 4 },
        subdivision: 'sixteenth',
        durationMinutes: 2,
      },
    ],
  },
];
