// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  heading: dynamic(() => import("./Heading")),
  image: dynamic(() => import("./Image")),
  list: dynamic(() => import("./List")),
  quote: dynamic(() => import("./Quote")),
  text: dynamic(() => import("./Text")),
};
